In [10]:
for i in range(1, 10):
    temp = []
    print(f'Очень счастливые числа в диапазоне {i*1000} : {(i+1)*1000}:')
    print()
    for j in range(i*1000, (i + 1)*1000):
        num = str(j)
        if int(num[0]) + int(num[1]) == int(num[2]) + int(num[3]):
            temp.append(j)
    print(*temp, sep='\t')
    print()

Очень счастливые числа в диапазоне 1000 : 2000:

1001	1010	1102	1111	1120	1203	1212	1221	1230	1304	1313	1322	1331	1340	1405	1414	1423	1432	1441	1450	1506	1515	1524	1533	1542	1551	1560	1607	1616	1625	1634	1643	1652	1661	1670	1708	1717	1726	1735	1744	1753	1762	1771	1780	1809	1818	1827	1836	1845	1854	1863	1872	1881	1890	1919	1928	1937	1946	1955	1964	1973	1982	1991

Очень счастливые числа в диапазоне 2000 : 3000:

2002	2011	2020	2103	2112	2121	2130	2204	2213	2222	2231	2240	2305	2314	2323	2332	2341	2350	2406	2415	2424	2433	2442	2451	2460	2507	2516	2525	2534	2543	2552	2561	2570	2608	2617	2626	2635	2644	2653	2662	2671	2680	2709	2718	2727	2736	2745	2754	2763	2772	2781	2790	2819	2828	2837	2846	2855	2864	2873	2882	2891	2929	2938	2947	2956	2965	2974	2983	2992

Очень счастливые числа в диапазоне 3000 : 4000:

3003	3012	3021	3030	3104	3113	3122	3131	3140	3205	3214	3223	3232	3241	3250	3306	3315	3324	3333	3342	3351	3360	3407	3416	3425	3434	3443	3452	3461	3470	3508	3517	3526	3535	3544	3553	3562	3571	3580	3609	3618	3627	3636	3645	3654	3663	3672	3681	3690	3719	3728	3737	3746	3755	3764	3773	3782	3791	3829	3838	3847	3856	3865	3874	3883	3892	3939	3948	3957	3966	3975	3984	3993

Очень счастливые числа в диапазоне 4000 : 5000:

4004	4013	4022	4031	4040	4105	4114	4123	4132	4141	4150	4206	4215	4224	4233	4242	4251	4260	4307	4316	4325	4334	4343	4352	4361	4370	4408	4417	4426	4435	4444	4453	4462	4471	4480	4509	4518	4527	4536	4545	4554	4563	4572	4581	4590	4619	4628	4637	4646	4655	4664	4673	4682	4691	4729	4738	4747	4756	4765	4774	4783	4792	4839	4848	4857	4866	4875	4884	4893	4949	4958	4967	4976	4985	4994

Очень счастливые числа в диапазоне 5000 : 6000:

5005	5014	5023	5032	5041	5050	5106	5115	5124	5133	5142	5151	5160	5207	5216	5225	5234	5243	5252	5261	5270	5308	5317	5326	5335	5344	5353	5362	5371	5380	5409	5418	5427	5436	5445	5454	5463	5472	5481	5490	5519	5528	5537	5546	5555	5564	5573	5582	5591	5629	5638	5647	5656	5665	5674	5683	5692	5739	5748	5757	5766	5775	5784	5793	5849	5858	5867	5876	5885	5894	5959	5968	5977	5986	5995

Очень счастливые числа в диапазоне 6000 : 7000:

6006	6015	6024	6033	6042	6051	6060	6107	6116	6125	6134	6143	6152	6161	6170	6208	6217	6226	6235	6244	6253	6262	6271	6280	6309	6318	6327	6336	6345	6354	6363	6372	6381	6390	6419	6428	6437	6446	6455	6464	6473	6482	6491	6529	6538	6547	6556	6565	6574	6583	6592	6639	6648	6657	6666	6675	6684	6693	6749	6758	6767	6776	6785	6794	6859	6868	6877	6886	6895	6969	6978	6987	6996

Очень счастливые числа в диапазоне 7000 : 8000:

7007	7016	7025	7034	7043	7052	7061	7070	7108	7117	7126	7135	7144	7153	7162	7171	7180	7209	7218	7227	7236	7245	7254	7263	7272	7281	7290	7319	7328	7337	7346	7355	7364	7373	7382	7391	7429	7438	7447	7456	7465	7474	7483	7492	7539	7548	7557	7566	7575	7584	7593	7649	7658	7667	7676	7685	7694	7759	7768	7777	7786	7795	7869	7878	7887	7896	7979	7988	7997

Очень счастливые числа в диапазоне 8000 : 9000:

8008	8017	8026	8035	8044	8053	8062	8071	8080	8109	8118	8127	8136	8145	8154	8163	8172	8181	8190	8219	8228	8237	8246	8255	8264	8273	8282	8291	8329	8338	8347	8356	8365	8374	8383	8392	8439	8448	8457	8466	8475	8484	8493	8549	8558	8567	8576	8585	8594	8659	8668	8677	8686	8695	8769	8778	8787	8796	8879	8888	8897	8989	8998

Очень счастливые числа в диапазоне 9000 : 10000:

9009	9018	9027	9036	9045	9054	9063	9072	9081	9090	9119	9128	9137	9146	9155	9164	9173	9182	9191	9229	9238	9247	9256	9265	9274	9283	9292	9339	9348	9357	9366	9375	9384	9393	9449	9458	9467	9476	9485	9494	9559	9568	9577	9586	9595	9669	9678	9687	9696	9779	9788	9797	9889	9898	9999

In [11]:
from collections import namedtuple
import pickle
Animal = namedtuple('Animal', ['name', 'family', 'sex', 'color'])
with open('data.pkl', 'rb') as file:
    info = pickle.load(file)
for item in info:
    for key, value in zip(Animal._fields, item):
        print(f'{key}: {value}')
    print()

name: Alex
family: dogs
sex: m
color: brown

name: Nancy
family: cats
sex: w
color: white

name: Sam
family: dogs
sex: m
color: brown

name: Misha
family: hedgehogs
sex: m
color: black

name: Fredd
family: cats
sex: m
color: white

name: Python
family: snakes
sex: w
color: white

name: Crispy
family: cats
sex: w
color: white

name: Adam
family: hedgehogs
sex: m
color: black

name: Daddy
family: snakes
sex: m
color: brown

name: Mickey
family: hedgehogs
sex: m
color: brown

name: Tom
family: cats
sex: m
color: white

name: Jerry
family: snakes
sex: m
color: brown

name: Chip
family: hedgehogs
sex: m
color: white

In [20]:
from collections import namedtuple

User = namedtuple('User', ['name', 'surname', 'email', 'plan'])

users = [User('Mary', 'Griffin', 'sonnen@yahoo.com', 'Basic'),
         User('Brenda', 'Young', 'retoh@outlook.com', 'Silver'),
         User('Kathleen', 'Lyons', 'balchen@att.net', 'Gold'),
         User('Pamela', 'Hicks', 'corrada@sbcglobal.net', 'Silver'),
         User('William', 'Townsend', 'kosact@verizon.net', 'Gold'),
         User('Clayton', 'Morris', 'berserk@yahoo.com', 'Silver'),
         User('Dorothy', 'Dennis', 'sequin@live.com', 'Gold'),
         User('Tyler', 'Walker', 'noahb@comcast.net', 'Basic'),
         User('Joseph', 'Moore', 'ylchang@sbcglobal.net', 'Silver'),
         User('Kenneth', 'Richardson', 'tbusch@me.com', 'Bronze'),
         User('Stephanie', 'Bush', 'neuffer@live.com', 'Gold'),
         User('Gregory', 'Hughes', 'juliano@att.net', 'Basic'),
         User('Tracy', 'Wallace', 'sblack@me.com', 'Silver'),
         User('Russell', 'Smith', 'isaacson@comcast.net', 'Bronze'),
         User('Megan', 'Patterson', 'hoangle@outlook.com', 'Basic')]

users = sorted(users, key=lambda x: (('Gold', 'Silver', 'Bronze', 'Basic').index(x.plan), x.email))

for item in users:
    print(item.name, item.surname)
    print(f'  Email: {item.email}')
    print(f'  Plan: {item.plan}')
    print()

Kathleen Lyons
  Email: balchen@att.net
  Plan: Gold

William Townsend
  Email: kosact@verizon.net
  Plan: Gold

Stephanie Bush
  Email: neuffer@live.com
  Plan: Gold

Dorothy Dennis
  Email: sequin@live.com
  Plan: Gold

Clayton Morris
  Email: berserk@yahoo.com
  Plan: Silver

Pamela Hicks
  Email: corrada@sbcglobal.net
  Plan: Silver

Brenda Young
  Email: retoh@outlook.com
  Plan: Silver

Tracy Wallace
  Email: sblack@me.com
  Plan: Silver

Joseph Moore
  Email: ylchang@sbcglobal.net
  Plan: Silver

Russell Smith
  Email: isaacson@comcast.net
  Plan: Bronze

Kenneth Richardson
  Email: tbusch@me.com
  Plan: Bronze

Megan Patterson
  Email: hoangle@outlook.com
  Plan: Basic

Gregory Hughes
  Email: juliano@att.net
  Plan: Basic

Tyler Walker
  Email: noahb@comcast.net
  Plan: Basic

Mary Griffin
  Email: sonnen@yahoo.com
  Plan: Basic

In [41]:
import csv
from datetime import datetime
from collections import namedtuple
with open('meetings.csv', 'rt', encoding='utf-8') as file:
    data = list(csv.DictReader(file))
Friend = namedtuple('Friend', ['name', 'time'])
data1 = [Friend(x['surname']+' '+x['name'], 
        datetime.strptime(x['meeting_date']+' '+x['meeting_time'], '%d.%m.%Y %H:%M')) for x in data]
data2 = [x.name for x in sorted(data1, key=lambda x: x.time)]
print(*data2, sep='\n')

Гудцев Таймураз
Харисов Артур
Базиев Герман
Макоев Руслан
Найфонов Сослан
Короев Аслан
Дедегкаев Давид
Уртаева Илина
Бекузарова Фатима
Акоева Лера
Белов Глеб
Букулова Диана
Гусейнова Марьям
Набокова Алиса
Чередник Марк
Перчиков Максим
Идрисов Баграт
Абаев Михаил
Елькина Мария
Кораев Давид
Акоева Амина
Денисов Тимофей
Алдатов Сармат
Зеленчук Александра
Тарасов Станислав
Гапбаев Герман
Рыжая Ярослава
Джикаев Таму
Балаболка Вероника
Гагиев Геор
Козаев Роберт
Габараев Артур
Юлдашев Хандамир
Кодзаев Георгий
Дедегкаев Дамир
Момотов Владислав
Щербак Юрий
Чуприков Максим
Тиникашвили Давид
Кораев Артур
Цивинская Анна
Солдатенков Илья
Туткевич Юрий
Маилян Кирилл
Джиоева Марина
Салбиев Максим
Чен Владимир
Капустин Егор
Туаллагов Давид
Губаев Герман
Кузнецов Станислав
Албегов Хетаг
Битиев Сослан
Мусиков Андраник
Уртаева Дзера
Гадзиев Георгий
Епхиева Алика
Шилин Александр

In [50]:
from collections import defaultdict

data = [('Books', 1343), ('Books', 1166), ('Merch', 616), ('Courses', 966), ('Merch', 1145), ('Courses', 1061), ('Books', 848), ('Courses', 964), ('Tutorials', 832), ('Merch', 642), ('Books', 815), ('Tutorials', 1041), ('Books', 1218), ('Tutorials', 880), ('Books', 1003), ('Merch', 951), ('Books', 920), ('Merch', 729), ('Tutorials', 977), ('Books', 656)]

data1 = defaultdict(int)
for i in data:
    data1[i[0]] = data1[i[0]] + i[1]
for key in sorted(data1.keys()):
    print(f'{key}: ${data1[key]}')

Books: $7969
Courses: $2991
Merch: $4083
Tutorials: $3730

In [52]:
from collections import defaultdict

staff = [('Sales', 'Robert Barnes'), ('Developing', 'Thomas Porter'), ('Accounting', 'James Wilkins'), ('Sales', 'Connie Reid'),
('Accounting', 'Brenda Davis'), ('Developing', 'Miguel Norris'), ('Accounting', 'Linda Hudson'), ('Developing', 'Deborah George'), 
('Developing', 'Nicole Watts'), ('Marketing', 'Billy Lloyd'), ('Sales', 'Charlotte Cox'), ('Marketing', 'Bernice Ramos'),
('Sales', 'Jose Taylor'), ('Sales', 'Katie Warner'), ('Accounting', 'Steven Diaz'), ('Accounting', 'Kimberly Reynolds'), 
('Accounting', 'John Watts'), ('Accounting', 'Dale Houston'), ('Developing', 'Arlene Gibson'), ('Marketing', 'Joyce Lawrence'), 
('Accounting', 'Rosemary Garcia'), ('Marketing', 'Ralph Morgan'), ('Marketing', 'Sam Davis'), ('Marketing', 'Gail Hill'), 
('Accounting', 'Michelle Wright'), ('Accounting', 'Casey Jenkins'), ('Sales', 'Evelyn Martin'), ('Accounting', 'Aaron Ferguson'), 
('Marketing', 'Andrew Clark'), ('Marketing', 'John Gonzalez'), ('Developing', 'Wilma Woods'), ('Sales', 'Marie Cooper'), 
('Accounting', 'Kay Scott'), ('Sales', 'Gladys Taylor'), ('Accounting', 'Ann Bell'), ('Accounting', 'Craig Wood'), 
('Accounting', 'Gloria Higgins'), ('Marketing', 'Mario Reynolds'), ('Marketing', 'Helen Taylor'), ('Marketing', 'Mary King'), 
('Accounting', 'Jane Jackson'), ('Marketing', 'Carol Peters'), ('Sales', 'Alicia Mendoza'), ('Accounting', 'Edna Cunningham'),
('Developing', 'Joyce Rivera'), ('Sales', 'Joseph Lee'), ('Sales', 'John White'), ('Marketing', 'Charles Bailey'), 
('Sales', 'Chester Fernandez'), ('Sales', 'John Washington')]

data = defaultdict(int)
for item in staff:
    data[item[0]] = data[item[0]] + 1
for key in sorted(data.keys()):
    print(f'{key}: {data[key]}')

Accounting: 17
Developing: 7
Marketing: 13
Sales: 13

In [59]:
from collections import defaultdict

staff_broken = [('Developing', 'Miguel Norris'), ('Sales', 'Connie Reid'), ('Sales', 'Joseph Lee'), ('Marketing', 'Carol Peters'), ('Accounting', 'Linda Hudson'), ('Accounting', 'Ann Bell'), ('Marketing', 'Ralph Morgan'), ('Accounting', 'Gloria Higgins'), ('Developing', 'Wilma Woods'), ('Developing', 'Wilma Woods'), ('Marketing', 'Bernice Ramos'), ('Marketing', 'Joyce Lawrence'), ('Accounting', 'Craig Wood'), ('Developing', 'Nicole Watts'), ('Sales', 'Jose Taylor'), ('Accounting', 'Linda Hudson'), ('Accounting', 'Edna Cunningham'), ('Sales', 'Jose Taylor'), ('Marketing', 'Helen Taylor'), ('Accounting', 'Kimberly Reynolds'), ('Marketing', 'Mary King'), ('Sales', 'Joseph Lee'), ('Accounting', 'Gloria Higgins'), ('Marketing', 'Andrew Clark'), ('Accounting', 'John Watts'), ('Accounting', 'Rosemary Garcia'), ('Accounting', 'Steven Diaz'), ('Marketing', 'Mary King'), ('Sales', 'Gladys Taylor'), ('Developing', 'Thomas Porter'), ('Accounting', 'Brenda Davis'), ('Sales', 'Connie Reid'), ('Sales', 'Alicia Mendoza'), ('Marketing', 'Mario Reynolds'), ('Sales', 'John White'), ('Developing', 'Joyce Rivera'), ('Accounting', 'Steven Diaz'), ('Developing', 'Arlene Gibson'), ('Sales', 'Robert Barnes'), ('Sales', 'Charlotte Cox'), ('Accounting', 'Craig Wood'), ('Marketing', 'Carol Peters'), ('Marketing', 'Ralph Morgan'), ('Accounting', 'Kay Scott'), ('Sales', 'Evelyn Martin'), ('Marketing', 'Billy Lloyd'), ('Sales', 'Gladys Taylor'), ('Developing', 'Deborah George'), ('Sales', 'Charlotte Cox'), ('Marketing', 'Sam Davis'), ('Sales', 'John White'), ('Sales', 'Marie Cooper'), ('Marketing', 'John Gonzalez'), ('Sales', 'John Washington'), ('Sales', 'Chester Fernandez'), ('Sales', 'Alicia Mendoza'), ('Sales', 'Katie Warner'), ('Accounting', 'Jane Jackson'), ('Sales', 'Chester Fernandez'), ('Marketing', 'Charles Bailey'), ('Marketing', 'Gail Hill'), ('Accounting', 'Casey Jenkins'), ('Accounting', 'James Wilkins'), ('Accounting', 'Casey Jenkins'), ('Marketing', 'Mario Reynolds'), ('Accounting', 'Aaron Ferguson'), ('Accounting', 'Kimberly Reynolds'), ('Sales', 'Robert Barnes'), ('Accounting', 'Aaron Ferguson'), ('Accounting', 'Jane Jackson'), ('Developing', 'Deborah George'), ('Accounting', 'Michelle Wright'), ('Accounting', 'Dale Houston')]
departments = defaultdict(list)
for item in staff_broken:
    if item[1] not in departments[item[0]]:
        departments[item[0]].append(item[1])
    
for key in departments:
    departments[key] = sorted(departments[key]) 
for key in sorted(departments.keys()):
    print(f'{key}:', end=' ')
    print(*departments[key], sep=', ')

Accounting: Aaron Ferguson, Ann Bell, Brenda Davis, Casey Jenkins, Craig Wood, Dale Houston, Edna Cunningham, Gloria Higgins, James Wilkins, Jane Jackson, John Watts, Kay Scott, Kimberly Reynolds, Linda Hudson, Michelle Wright, Rosemary Garcia, Steven Diaz
Developing: Arlene Gibson, Deborah George, Joyce Rivera, Miguel Norris, Nicole Watts, Thomas Porter, Wilma Woods
Marketing: Andrew Clark, Bernice Ramos, Billy Lloyd, Carol Peters, Charles Bailey, Gail Hill, Helen Taylor, John Gonzalez, Joyce Lawrence, Mario Reynolds, Mary King, Ralph Morgan, Sam Davis
Sales: Alicia Mendoza, Charlotte Cox, Chester Fernandez, Connie Reid, Evelyn Martin, Gladys Taylor, John Washington, John White, Jose Taylor, Joseph Lee, Katie Warner, Marie Cooper, Robert Barnes